# Generated by Django 6.0.1 on 2026-01-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='clara_khumalo_dev_portfolio/media/videos/')),
                ('tools', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
