# Generated by Django 6.0.1 on 2026-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
