# Generated by Django 6.0.1 on 2026-01-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_alter_aboutme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.FileField(upload_to='media/images/'),
        ),
    ]
