# Generated by Django 6.0.1 on 2026-01-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='assets/images/')),
                ('profile_link', models.URLField()),
                ('social_username', models.CharField(max_length=255)),
            ],
        ),
    ]
