# Generated by Django 6.0.1 on 2026-01-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socials',
            name='image',
            field=models.FileField(upload_to='media/images/'),
        ),
    ]
