# Generated by Django 6.0.1 on 2026-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('github_profile_link', models.URLField()),
                ('linkedin_profile_link', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
