# Generated by Django 6.0.1 on 2026-01-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_And_Proficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('extras', models.CharField(max_length=255)),
                ('skill_percentage', models.CharField(max_length=255)),
            ],
        ),
    ]
