# Generated by Django 6.0.1 on 2026-01-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_and_proficiencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills_and_proficiencies',
            name='skill_percentage',
            field=models.IntegerField(),
        ),
    ]
