# Generated by Django 6.0.1 on 2026-01-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills_and_proficiencies', '0002_alter_skills_and_proficiencies_skill_percentage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills_And_Proficiencies',
            new_name='SkillsAndProficiencies',
        ),
    ]
