# Generated by Django 6.0.1 on 2026-01-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_and_proficiencies', '0003_rename_skills_and_proficiencies_skillsandproficiencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsandproficiencies',
            name='hover',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
